### ISSUE TITLE
OSC not working on OS X 

### ISSUE THREAD

**Issue by gllmAR** [mapmapteam/mapmap#103]
When launching  on OS X there is no confirmation  
Listening osc.udp://localhost:12345

gllm:MacOS gllm$ ./MapMap 
OS X detected. Set environment for GStreamer-SDK support.
 * GST_PLUGIN_PATH=Library/Frameworks/GStreamer.framework/Libraries
 * GST_DEBUG=2
void QCocoaWindow::syncWindowState(Qt::WindowState) invalid window content view size, check your window geometry
Using GStreamer version  1 . 2 . 4
Video support: yes
QIODevice::read: device not open

**Comment by aalex** [comment]
We need to build it against liblo, but OS X lacks pkg-config.

**Comment by aalex** [comment]
Fixed in 0.3.1 (using absolute paths, for now)
