### ISSUE TITLE
Our custom Qt colored theme doesn't work when MapMap is not launched from its source directory

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#110]
ça affecte la lisibilité.

**Comment by aalex** [comment]
Makes it hard to read. 

It is also the case on OS X.

**Comment by sofian** [comment]
@aalex Is this bug still valid?

**Comment by sofian** [comment]
I tried launching mapmap from another folder on both Ubuntu 15.10 and SX 10.11 and the colors are fine. Only the toolbar's background stays "pale" in OSX but that's true whether we start it from the same folder or not. Can you confirm the behavior still happens on your side @aalex ?

**Comment by aalex** [comment]
I remember it doesn't work on OS X. That's a separate bug, though. See Our custom Qt colored theme doesn't work on OS X, the toolbar's background is pale #223
