### ISSUE TITLE
Do not save the state of windows appearance

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#112]
Le state saving de l'apparence est pleine de bogues: il vaudrait peut-être mieux s'en débarrasser.

**Comment by baydam** [comment]
@aalex je comprend pas vraiment ce que tu veux dire par la

**Comment by aalex** [comment]
C'est que l'on garde la position des fenêtres, tabs et autres widgets dans le state saving. Parfois, ça fait que l'on lance le logiciel, et on ne voit pas du tout une section au complet du logiciel.

Dans d'autres cas, quand on fait des changements dans le logiciel, ça fait que ce qui était sauvegardé dans le state saving ne fonctionne plus du tout avec la nouvelle disposition des widgets. Il faut alors lancer mapmap avec l'option --reset-settings

**Comment by sofian** [comment]
Il faudrait peut-être délimiter ce que l'on souhaite garder et ce que l'on souhaite rejeter. Il me semble que certaines propriétés des éléments graphiques devraient être préservés, tels que la taille des canvas.

Ma suggestion: "Parfois, ça fait que l'on lance le logiciel, et on ne voit pas du tout une section au complet du logiciel" --> Tester quels settings en particulier causent problème et enlever seulement ceux-ci.

Pour ce qui est du 2e problème (compatibilité entre les versions) le workaround "reset settings" me semble ok.

**Comment by sofian** [comment]
Idée: on pourrait conserver la version du logiciel dans le fichier de settings: si la version change, on fait automatiquement un reset. De cette façon dans un changement de version nos users qui ne savent pas utiliser la commandline ne vont pas virer fous!

**Comment by baydam** [comment]
Quelqu'un peut fermer ce ticket j'arrive toujours pas a le reproduire
