### ISSUE TITLE
Audio playback of the video files played

### ISSUE THREAD

**Issue by gllmAR** [mapmapteam/mapmap#114]
Sound input  and sound playback ?

**Comment by vliaskov** [comment]
It's straightforward to enable the audio pipelines for each input. However, I suspect we want audio playback only for enabled mappings or only for the front (topmost) active mapping... what's the expected playback behaviour? Enabling audio selectively per mapping would probably require some appsink/second appsrc pipeline, or switching between a fakesink and a real audiosink element dynamically for the enabled mapping/input, so this behaviour would require a bit more work.

**Comment by gllmAR** [comment]
Volume contro on each playing source?

**Comment by vliaskov** [comment]
I added a volume property in each paint. Let me know if it works for you (already tested and works locally).

**Comment by sofian** [comment]
I think in general Mapmap being a video mapping tool I am unsure whether we really need to support audio. The only case I can see is if you have a video with a soundtrack and want to make sure the sound is in sync. But we should not turn Mapmap into a sound mixing tool if possible. I don't know what's the best approach, I think a simple volume control in the properties like vliaskov implemented is a good approach. We can see how that works out.

**Comment by sofian** [comment]
This goes in 0.4.
