### ISSUE TITLE
Menu bar is not visible under OS X

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#126]
OS: OS X 10.9.3
MapMap version: branch develop, before releasing 0.3.0

Launching MapMap. The menu bar is not visible. It should be.

See attached screenshot.

![capture d ecran 2015-07-17 a 17 09 39](https://cloud.githubusercontent.com/assets/293677/8757283/f2d37ab4-2ca6-11e5-9314-e3a030ffdb1f.png)

**Comment by sofian** [comment]
Tested it on OSX 10.11 and the menu appears fine. @aalex You still got that error?

**Comment by sofian** [comment]
However the zoom bar does not appear. Is that what you were referring to?

**Comment by sofian** [comment]
Actually: I was able to reproduce a similar problem when clicking on the "expand" button (little green bullet on top-left next to the red and yellow ones). However I think in that case it is normal: you can bring back the menu by hovering the mouse on the of the screen.

**Comment by sofian** [comment]
I don't have this bug. Closing.
