### ISSUE TITLE
Errors and warning while building the OS X app

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#127]
ERROR: no file at "/Library/lib/GStreamer.framework/Versions/1.0/GStreamer" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/accessible/libqtaccessiblequick.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/accessible/libqtaccessiblequick.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/accessible/libqtaccessiblewidgets.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/accessible/libqtaccessiblewidgets.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/audio/libqtaudio_coreaudio.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/audio/libqtaudio_coreaudio.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/imageformats/libqdds.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/imageformats/libqdds.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/imageformats/libqgif.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/imageformats/libqgif.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/imageformats/libqicns.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/imageformats/libqicns.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/imageformats/libqico.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/imageformats/libqico.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/imageformats/libqjp2.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/imageformats/libqjp2.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/imageformats/libqjpeg.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/imageformats/libqjpeg.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/imageformats/libqmng.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/imageformats/libqmng.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/imageformats/libqtga.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/imageformats/libqtga.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/imageformats/libqtiff.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/imageformats/libqtiff.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/imageformats/libqwbmp.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/imageformats/libqwbmp.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/imageformats/libqwebp.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/imageformats/libqwebp.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/mediaservice/libqavfcamera.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/mediaservice/libqavfcamera.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/mediaservice/libqavfmediaplayer.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/mediaservice/libqavfmediaplayer.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/mediaservice/libqqt7engine.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/mediaservice/libqqt7engine.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/mediaservice/libqtmedia_audioengine.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/mediaservice/libqtmedia_audioengine.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/platforms/libqcocoa.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/platforms/libqcocoa.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/platforms/libqminimal.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/platforms/libqminimal.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/platforms/libqoffscreen.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/platforms/libqoffscreen.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/playlistformats/libqtmultimedia_m3u.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/playlistformats/libqtmultimedia_m3u.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/position/libqtposition_positionpoll.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/position/libqtposition_positionpoll.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/printsupport/libcocoaprintersupport.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/printsupport/libcocoaprintersupport.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/qml1tooling/libqmldbg_inspector.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/qml1tooling/libqmldbg_inspector.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/qml1tooling/libqmldbg_tcp_qtdeclarative.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/qml1tooling/libqmldbg_tcp_qtdeclarative.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/sensorgestures/libqtsensorgestures_plugin.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/sensorgestures/libqtsensorgestures_plugin.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/sensorgestures/libqtsensorgestures_shakeplugin.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/sensorgestures/libqtsensorgestures_shakeplugin.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/sensors/libqtsensors_dummy.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/sensors/libqtsensors_dummy.dylib" 
ERROR: file copy failed from "/Users/aalex/Qt/5.3/clang_64/plugins/sensors/libqtsensors_generic.dylib" 
ERROR:  to "MapMap.app/Contents/PlugIns/sensors/libqtsensors_generic.dylib" 
WARNING: 
WARNING: "MapMap.app/Contents/Resources/qt.conf" already exists, will not overwrite. 
WARNING: To make sure the plugins are loaded from the correct location, 
WARNING: please make sure qt.conf contains the following lines: 
WARNING: [Paths] 
WARNING:   Plugins = PlugIns

**Comment by sofian** [comment]
Oh yes I guess I had that problem when trying to install on OSX.
The issue was that the install instructions on OSX seem outdated: they tell us to install GStreamer 0.1 but what we actually need to install is 1.0. If you install GStreamer 1.0 it should fix the issue.

**Comment by aalex** [comment]
Get it from there: http://gstreamer.freedesktop.org/data/pkg/osx/
Any version in there should work. (they should all be ABI-compatible)
So, use this one:
http://gstreamer.freedesktop.org/data/pkg/osx/1.5.2/gstreamer-1.0-1.5.2-x86_64.pkg

Le ven. 17 juil. 2015 à 18:00, Sofian Audry <notifications@github.com> a
écrit :

**Comment by sofian** [comment]
This should be reflected in the INSTALL procedure and on the website.

**Comment by aalex** [comment]
I took it in the INSTALL document, I believe.
It might be missing in the file that comes with the DMG archive.

Le ven. 17 juil. 2015 18:19, Sofian Audry <notifications@github.com> a
écrit :

**Comment by sofian** [comment]
Fixed.
