### ISSUE TITLE
Crash on changing mappings dimension

### ISSUE THREAD

**Issue by maxdee** [mapmapteam/mapmap#128]
When changing the dimention of a quad via the side bar from width or height 2 to anything else it crashes IF the output window is open. 
in 0.3.1 on crunchbang waldorf AKA debian wheezy
`ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/i386-linux-gnu/qt5/QtCore/qvector.h, line 385
Aborted`

**Comment by sofian** [comment]
Is this in branch develop? You are talking about columns/rows right?

**Comment by maxdee** [comment]
Yes yes, does not crash for you?

**Comment by sofian** [comment]
Oh yes it does lol!

**Comment by sofian** [comment]
Fixed by 9b6f49e9ccc69974876c72aa8e57fa53ac060100

**Comment by maxdee** [comment]
Cool, tested.
