### ISSUE TITLE
Design icons for new functionalities in 0.4

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#132]
Toolbar and menu:
- "sticky vertices"
- test signal display
- webcam

Layer editor: toggles for visible/invisible, solo and lock/unlock.

Exemples:
http://verysimpledesigns.com/vsd_media/inkscape_tutorial_seamless/vsd_seamless_hide_export_mask_layer.png
https://documentation.apple.com/en/logicpro/usermanual/Art/S08/S0854_SoloButton.png

**Comment by aalex** [comment]
We want smaller icons for small displays, too.

**Comment by aalex** [comment]
https://github.com/mapmapteam/mapmap/wiki/Missing-icons-for-MapMap
