### ISSUE TITLE
Video playback is broken

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#135]
MapMap doesn't play video files anymore!

The code for the GStreamer pipeline is here:
https://github.com/mapmapteam/mapmap/blob/develop/MediaImpl.cpp

See also #124 (probably related)

**Comment by sofian** [comment]
@aalex Should we close this one?

**Comment by sofian** [comment]
I will close this cause I believe it has been fixed. Feel free to reopen if it is not the case.
