### ISSUE TITLE
Copy constructor bug when compiling

### ISSUE THREAD

**Issue by jukea** [mapmapteam/mapmap#14]
![screen shot 2014-01-30 at 11 53 06](https://f.cloud.github.com/assets/155702/2042368/51c7ba06-89d0-11e3-8c25-e0b7e7efe768.png)

I have this problem when compiling branch "develop". Any clue?

**Comment by sofian** [comment]
This is a very old issue. Closing.

**Comment by jukea** [comment]
I'm not satisfied with this resolution  ! Reopen and switch to QPointF !

sorry , spurious comment / Resume normal life

Also, Congrats, Dr. !

**Comment by sofian** [comment]
We switched to QPointF a long time ago. ;)
Thanks man!
