### ISSUE TITLE
Show all the mappings of a paint source

### ISSUE THREAD

**Issue by maxdee** [mapmapteam/mapmap#142]
Small but important improvement. 
It would be helpful to be able to view all the mappings on a source. Can we draw all the mappings in red and the one selected as it is? Snapping to other mappings like in the output window would be great.

![mapmap_mapping_view](https://cloud.githubusercontent.com/assets/1138961/10843357/ee30844e-7ef8-11e5-9129-6baa77e6468b.png)

(I really need to get going on cpp + qt)

**Comment by maxdee** [comment]
Would be nice to solve this!

**Comment by sofian** [comment]
Interesting: we'll do it for 0.5.

**Comment by maxdee** [comment]
BUMP @baydam
