### ISSUE TITLE
The user doesn't need to see the undo stack

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#145]
It could still be available, but as a menu item in a separate window, or so.

**Comment by sofian** [comment]
It's in a separate tab, isn't that good enough?

**Comment by sofian** [comment]
I suggest a menu "View" with a checkable option "Undo stack". When it is checked, the undo stack appears in a tab (like it is right now).

**Comment by baydam** [comment]
It's a good idea but it can also be in preference dialogue with a checkable option

**Comment by sofian** [comment]
I think in the View menu it's better. It's the kind of thing that most people will want to have all the time, or be able to popup quickly. Preferences are for settings that are more permanent / immutable.

**Comment by sofian** [comment]
Closed by Dame.
