### ISSUE TITLE
There should be no white rectangle around the fullscreen window

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#156]

**Comment by sofian** [comment]
Screenshot?

**Comment by aalex** [comment]
![fullscreen](https://cloud.githubusercontent.com/assets/293677/11628151/beff23be-9cbd-11e5-80a5-419639013956.png)
![output_window](https://cloud.githubusercontent.com/assets/293677/11628156/c1ce8fc6-9cbd-11e5-96e7-a50a9c8c0afd.png)

**Comment by aalex** [comment]
(note that the cursor was not visible on the fullscreen output window, which is good. The screeshot shows it, but it wasn't visible - it must be a bug with the screenshot application, plus the window server)

**Comment by loshermanos** [comment]
It s cool to have cursor and pointer at thé output 
It alows the mapper to see exactly the horizontal and vertical when you map.
When you are in the dark mapping a lot of element it s sometimes difficult to to see the cursor .
Maybe it s god to have a button and shortcut to reveal it .
Best mike

Envoyé de mon iPhone
