### ISSUE TITLE
Test signal should look good in the mapping window

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#163]
It looks rather ok in the output window, but we should make sure it also looks good in the mapping view port.

**Comment by sofian** [comment]
Is it really necessary? In fact, in my opinion the mapping canvases should just not even have the test signal in them. The whole point of the test signal is to make adjustments on the projector and lighting.

**Comment by sofian** [comment]
@aalex Where are we on this? Is this still relevant?
