### ISSUE TITLE
Build doxygen documentation and upload to GitHub

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#165]
The doxygen documentation can be generated from mapmap main dir using: ./sh_build_doc.sh

Here's a guide (untested) on how to upload doxygen doc to github:
https://ncrmnt.org/2015/08/03/doxygen-gh-pages/

Before uploading make sure the doc is ok and up to date:
- Notice that the doxygen doc from MapMap seems really heavy: why?
- Make sure the main page is updated with all the authors, description, etc.

**Comment by aalex** [comment]
I think we could make it lighter by not compiling the images.

**Comment by sofian** [comment]
See also: http://rickfoosusa.blogspot.ca/2011/10/howto-use-doxygen-with-github.html

**Comment by baydam** [comment]
I agree with @aalex to not compiling the images. The doc is a bit heavy yet

**Comment by baydam** [comment]
Finally I've untracking images in gitignore files. Feel free to close this issues.

**Comment by aalex** [comment]
I still don't understand why the doxygen doc should be on Github. I would say: no, it should be built by each developer as needed.

**Comment by aalex** [comment]
I could be nice to upload it to a web site, but its large size, if we include the images, makes me hesitant to do so.

**Comment by aalex** [comment]
Ok. Seriously, it doesn't make any sense to upload that documentation to github. Please build it yourself on your computer. It takes a minute, and it will be up-to-date.
