### ISSUE TITLE
Add "zoom in/out/reset and fit to content" buttons

### ISSUE THREAD

**Issue by baydam** [mapmapteam/mapmap#185]
Add new buttons for zoom in, zoom out, reset zoom and fit in viewport
![boutons](https://cloud.githubusercontent.com/assets/4078827/12177621/edffbee8-b564-11e5-987d-535fdd35ce51.png)

**Comment by vliaskov** [comment]
Have the 4 zoom images been added to the develop branch? Compiling commit efe5c8f02a340cc708a563fac22b4e93fe44eff7 I get:

qmake
Project MESSAGE: MapMap version: 0.3.2
RCC: Error in 'mapmap.qrc': Cannot find file 'resources/images/icons/zoom_reset_w.png'
RCC: Error in 'mapmap.qrc': Cannot find file 'resources/images/icons/zoom_in_w.png'
RCC: Error in 'mapmap.qrc': Cannot find file 'resources/images/icons/zoom_out_w.png'
RCC: Error in 'mapmap.qrc': Cannot find file 'resources/images/icons/zoom_fit_w.png'

**Comment by baydam** [comment]
It's settled now d9ae92c

**Comment by baydam** [comment]
I apologize for the inconvenience
