### ISSUE TITLE
Fullscreen output window should hide menu bar

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#19]

**Comment by aalex** [comment]
We are still suffering from this issue. Observed on Ubuntu 14.04 with its default window manager.

**Comment by sofian** [comment]
@aalex Are you still observing that problem?
I know it's a common problem in Ubuntu...

**Comment by sofian** [comment]
Again, I'll assume this has been fixed cause I don't see it. Feel free to reopen.
