### ISSUE TITLE
Zoom-out using keys working

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#192]
Might be related to latest changes (zoom buttons).
Also, these might be two separated problems.

Normally CTRL= should result in zooming but does not.

I suggest looking at the increaseZoomLevel() method. I have also found that when scrolling, the increaseZoomLevel() method gets called but then somehow the decreaseZoomLevel() gets called for an unknown reason.

**Comment by baydam** [comment]
CTRL+ Plus may work on some kind of keyboard but CTRL+SHIFT+Plus should also be defined to handle these both cases.

**Comment by baydam** [comment]
Something like I've done on my last commit  eeca301
