### ISSUE TITLE
The position of the mappings from a loaded project is never right

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#194]
* Make the output window visible and fullscreen
* Create a project with some mappings
* Save it
* Quit and reopen MapMap
* Load the project
* Make the output window visible and fullscreen

The mappings should be at the same position they were saved at.

They are not. Even worse, sometimes they are lower, sometimes more to the left, etc.

**Comment by aalex** [comment]
Ça prend un second moniteur, ou un projecteur pour le tester, je crois.

**Comment by baydam** [comment]
Le bug se produit lorsqu'on a moins de deux mappings

**Comment by sofian** [comment]
I am unable to reproduce that bug.

**Comment by sofian** [comment]
The bug was confirmed by users in my department.
It might have been introduced with the revision of the saving/loading process.

Any chance one of you guys could do a git bisect to help find which specific commit introduced the bug?
