### ISSUE TITLE
UX Design document: Implement Cursor & Keyboard improvements

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#200]
See section 3 of the UX document.

Also to cleanup code, replace lines such as
 importVideoAction->setShortcut(tr("Ctrl+I"));
by:
 importVideoAction->setShortcut(Qt::CTRL + Qt::Key_I);
or whenever possible:
 newAction->setShortcut(QKeySequence::New);

**Comment by aalex** [comment]
I did the setShortcut(Qt::CTRL + Qt::Key_I);
