### ISSUE TITLE
UX Design document: implement main toolbar improvements

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#201]
From section 4, here is the list of agreed upon icons that should remain in the toolbar:

* Add Media Paint (single action to import video or image based on file extension)
* Add Color Paint
* Add Mesh Mapping
* Add Triangle Mapping
* Add Ellipse Mapping
* Fullscreen (basically there should not be two steps: popup output window then fullscreen, just fullscreen)
* Display Test Signal
* Play/Pause

**Comment by baydam** [comment]
Done
