### ISSUE TITLE
Add seek buttons in playback toolbar

### ISSUE THREAD

**Issue by baydam** [mapmapteam/mapmap#204]

**Comment by sofian** [comment]
How do you see this happening? Considering we have to seek in videos of different lengths...

**Comment by sofian** [comment]
Also not sure we want to add anything to the toolbar: we just decided to remove many buttons :)

**Comment by baydam** [comment]
Regarding the toolbar we must consider including in the preferences some checkboxes so the user can choose the icons he wants to display

**Comment by sofian** [comment]
Yes but that's another issue :)
