### ISSUE TITLE
Toggle display on menu bar shows two menu bars on Ubuntu 15.10

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#207]
Go to : View > Toolbars > Menu bar (deactivate)
Then reactivate.
See screenshot:
![screenshot from 2016-02-12 10-27-37](https://cloud.githubusercontent.com/assets/791244/13011150/62b00494-d173-11e5-8254-be9b2ef6eae5.png)

I think we should just not offer that option.

**Comment by aalex** [comment]
Effectivement. On ne devrait tout simplement pas offrir cette option, je crois bien... Non?

**Comment by baydam** [comment]
C'est vrai que c'est pas pratique avec ubuntu mais gnome as n'en besoin. peut etre qu'on dois juste ameliorer

**Comment by sofian** [comment]
Mais @baydam : quel est le but exactement de cacher la barre de menu? Pour la toolbar je comprends, mais la barre de menu me semble être essentielle,non?

**Comment by baydam** [comment]
Sur des desktop comme Ubuntu ou Mac le menu bar se situe au niveau de la barre de tache en haut mais avec gnome et autres ca prend de la place sur l'ecran et ca meme la plupart des logiciel comme Firefox(Iceweasel) par example le gere assez bien

**Comment by sofian** [comment]
Ok. Comment ça marche? Est-ce que la barre de menu s'affiche / s'éteint quand on glisse la souris au-dessus? Ce que je ne comprends pas c'est que l'option pour désactiver la barre de menu se trouve elle-même dans le menu. Du coup, une fois la barre menu désactivée, comment peut-on la ré-afficher?

**Comment by baydam** [comment]
Maintenant marche nickel sur gnome et autres mais je l'ai desactiver cette options sur Mac et Ubuntu. Si la barre de menu est desactiver il est aussitot cacher et en ce moment on peut le reafficher ou le recacher avec la Touche ALT. On peut aussi le reactiver dans les menus

**Comment by aalex** [comment]
Dans chrome, il y a un petit menu avec les trois barres horizontales, a la Bootstrap, lorsque la barre de menu n'est pas visible.Exemple: http://www.jqueryscript.net/images/jQuery-Plugin-For-Auto-Hiding-Bootstrap-Navbar.jpg
