### ISSUE TITLE
Activate fullscreen button only in dual screen mode

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#211]
Currently, the "fullscreen" button has different behaviors:
* in single-screen mode it pops-up the output window (non-fullscreen)
* in double-screen "mirroring" mode it brings fullscreen in the window
* in dual-screen mode it puts fullscreen window on the second screen

What we want instead is:
* in single-screen OR mirroring mode the output window should be closed and the fullscreen action should be disabled (ie. impossible to click/change)
* in dual-screen (non-mirroring) mode the fullscreen action should be available and possibly kept in its state (*)

(*) For example, if I:
* plug a second monitor
* toggle fullscreen to "ON"
* unplug monitor (fullscreen button stays "ON" but output window stops being displayed and becomes grayed-out / unselectable)
* re-plug second monitor: should bring back immediately the fullscreen on the 2nd screen

**Comment by aalex** [comment]
Yes!
