### ISSUE TITLE
Reorganize code base

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#212]
We have too much classes and shit at the root. We should reorganize code in a more logical way.

Here is a suggestion. We put all source code in a src/ folder with following subfolder:

== app ==
MainApplication.h
main.cpp

== core ==
Element.h
Maths.h
Mapping.h
MappingManager.h
MediaImpl.h
MetaObjectRegistry.h
MM.h
Paint.h
ProjectLabels.h
ProjectReader.h
ProjectWriter.h
Serializable.h
Shape.h
UidAllocator.h
Util.h

== shape ==
Ellipse.h
Mesh.h
Polygon.h
Quad.h
Shapes.h
Triangle.h

== gui ==
DestinationGLCanvas.h
MainWindow.h
MapperGLCanvas.h
MappingGui.h
OutputGLCanvas.h
OutputGLWindow.h
PaintGui.h
PreferencesDialog.h
ShapeControlPainter.h
ShapeGraphicsItem.h
SourceGLCanvas.h

== osc ==
ConcurrentQueue.h
OscInterface.h
OscReceiver.h

**Comment by aalex** [comment]
We should get rid of capital letters in file names. There are not well supported under Microsoft Windows.
I suggest a flat structure, within the src/ folder. It will be much, much easier to navigate through it! I like prefixes, like this:

* app_mainapplication.h
* app_main.cpp
* core_element.h
* core_maths.h
* core_mapping.h
* core_mappingmanager.h
* core_mediaimpl.h
* core_metaobjectregistry.h
* core_mm.h
* core_paint.h
* core_projectlabels.h
* core_projectreader.h
* core_projectwriter.h
* core_serializable.h
* core_shape.h
* core_uidallocator.h
* core_util.h
* shape_ellipse.h
* shape_mesh.h
* shape_polygon.h
* shape_quad.h
* shape_shapes.h
* shape_triangle.h
* gui_destinationglcanvas.h
* gui_mainwindow.h
* gui_mapperglcanvas.h
* gui_mappinggui.h
* gui_outputglcanvas.h
* gui_outputglwindow.h
* gui_paintgui.h
* gui_preferencesdialog.h
* gui_shapecontrolpainter.h
* gui_shapegraphicsitem.h
* gui_sourceglcanvas.h
* osc_concurrentqueue.h
* osc_oscinterface.h
* osc_oscreceiver.h

**Comment by sofian** [comment]
Ok I guess removing the capital letters makes sense for compatibility with Windows. However not sure the flat structure makes it more simple to navigate. To me scrolling down a long list of files is what makes it hard to navigate.

**Comment by aalex** [comment]
Think about us, poor people who use Vim, and not Eclipse, or so.

**Comment by aalex** [comment]
See Set up unit tests #332

**Comment by aalex** [comment]
Is this done? @sofian @baydam

**Comment by aalex** [comment]
To be verified.
