### ISSUE TITLE
Flickering video images when loading from the commandline

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#218]
This bug might be related to #217.
To reproduce:
* Create two video paints each with their mapping
* Save to a file
* Quit
* Start mapmap loading the file using the -f option

**Comment by sofian** [comment]
It does NOT do this if you open the file from the menu: just from the commandline.

**Comment by aalex** [comment]
It seems fine for me. It might be related to the prints in the console. We should print less messages from within VideoImpl.

**Comment by sofian** [comment]
Don't have the problem on OSX 10.11.
