### ISSUE TITLE
Compilation error: WARNING: Project ERROR: Unknown module(s) in QT: multimedia

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#251]
Just pulled from develop and I got an error with QT multimedia not being included. I am running Ubuntu 15.10. What is going on? Are we now using QT multimedia instead of GStreamer? If so we should discuss this.

**Comment by baydam** [comment]
I just use QT multimedia for get available cameras description for GUI implements

**Comment by sofian** [comment]
QT multimedia doesn't seem to be included by default. How did you install it on Ubuntu?

**Comment by baydam** [comment]
Maybe sudo apt-get install qt5-multimedia works. Of course I will update the INSTALL file

**Comment by baydam** [comment]
If i found the way to do that on Gstreamer side I'll bypass multimedia module

**Comment by sofian** [comment]
You need to install qtmultimedia5-dev
It compiles now. However it does not find my laptop camera on Ubuntu 15.04.

**Comment by sofian** [comment]
Sorry @baydam I did not read your comment. Got another problem #252 but maybe fixing it on GStreamer side will solve the issue.
