### ISSUE TITLE
[win 0.5 RC1] A couple suggestions / wishlist

### ISSUE THREAD

**Issue by jblanteigne** [mapmapteam/mapmap#261]
I assume most or some of these are already planned for future releases but here is what I noticed so far.

- When editing a mesh, I'd like to be able to group together points (add them to my selection) by holding down control so I can move them together.

- With Rectangle Meshes in the top viewer (where you crop the media), it would be useful to have a way to reset the mesh to the size of the media.

- I noticed that the X/Y coordinates (in the inspector in the bottom left) aren't relative to the size of the media. It would be easier to use this data if it made sense for the user. ie. The bottom left corner should be 0,0 and the top right corner should be 1920,1080. I'm not even sure what the 0,0 is based on at the moment.

Bezier curve control for shaping the meshes, at least for the ellipses because in real life when you're trying to match a circular structure, chances are that with the angle between the structure and the projector, the shape won't be perfect. Bezier make this really fast and easy to fix. My ideal way to transform the meshes is something like the tools in after effects or mocha.

Finally, personally the feature I need the most to actually use Mapmap is Spout input but you already know about this.

**Comment by sofian** [comment]
Hi and thanks for your feedback. I have created separate entries for your demands. I will now close this issue.
