### ISSUE TITLE
concentric squares around the cursor

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#272]

**Comment by sofian** [comment]
Could you provide a more extensive description?

**Comment by sofian** [comment]
Also is this related to #270 ?

**Comment by aalex** [comment]
It could be made so that it's easier for the user to know if they should move up/down left/right the cursor in order to click on what they need to.

**Comment by sofian** [comment]
Are you talking about the crosshair cursor or the normal cursor?

**Comment by aalex** [comment]
Les points de contrôle, pas le curseur. Il faut changer le titre du ticket

**Comment by aalex** [comment]
the crosshair, bro

**Comment by sofian** [comment]
This has been fixed.
