### ISSUE TITLE
Cannot run mapmap in french

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#278]
On Ubuntu 16.04 if I do `./mapmap --lang fr` the software is still in English. Same if I try to select "French (fr)" as language in preferences and restart.

**Comment by baydam** [comment]
It not really a bug! We need to translate the whole software before it's work

**Comment by baydam** [comment]
I have already tested it in a less small application

**Comment by sofian** [comment]
Wow really? Like if we do not translate ALL the terms it's not even working? That's nonsense!

**Comment by baydam** [comment]
Believe me I've trying hard to understand how it is possible but..

**Comment by sofian** [comment]
Have you tried asking on the Qt forum (IRC)?
It seems weird. But I totally believe you if you put it to the test!

**Comment by sofian** [comment]
But maybe people on the IRC chatroom would have solutions.

**Comment by sofian** [comment]
I found something interesting. It looks like some strings *do* get translated. These are the ones that are in the context QObject ie. that were implemented by calling ```QObject::tr(...)``` explicitly. For example:

**Comment by sofian** [comment]
I found the problem. It is related to the fact that we are using namespaces. The namespace (mmp) confuses the translation tools.
Example of someone who had a problem with namespaces: http://www.qtcentre.org/threads/59673-lupdate-fails-to-detect-context-for-class-in-namespace

**Comment by sofian** [comment]
I managed to make a test where I removed the namespaces and then the translations worked fine...

**Comment by sofian** [comment]
This is exactly the same issue that we got: http://www.qtcentre.org/threads/27422-solved-Translation-context-vs-namespaces

**Comment by sofian** [comment]
A workaround consists in changing the names to include the namespace in the .ts file. Example:
```
 <name>mmp::MainWindow</name>
```
This seems to fix the whole thing...
The problem is that it is not very sustainable to do so (we need to edit the .ts files by hand which is not practical).

**Comment by sofian** [comment]
Ok another issue was that we were using MM_BEGIN_NAMESPACE and MM_END_NAMESPACE in the files instead of directly using ```namespace mmp``` which confused ```lupdate```.

So I finally found a fix. Simple. We just need to replace MM_BEGIN_NAMESPACE and MM_END_NAMESPACE with the direct/complete text.
