### ISSUE TITLE
Document supported/best video formats for MapMap in a help section

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#279]
We still often have problems in Mapmap with unsupported video formats. It seems to be related to GStreamer and not easy to fix. Hence, what would be appropriate, would be to find what kind of video formats are appropriate for MapMap, taking into consideration (1) good formats for video mapping in general (2) formats that run smoothly on Mapmap on all platforms.

Once we have this, we need to document it on a webpage that we will add to our website.

Extra issues that could follow from this: (1) create a ffmpeg script to convert videos to appropriate format (2) when video cannot be read in Mapmap, popup an error message that prevents the video from being loaded, and that refers the user to the format page documentation.

**Comment by aalex** [comment]
I started a wiki page that will be included in the About dialog, and probably moved later somewhere else, in a documentation window. https://github.com/mapmapteam/mapmap/wiki/Video-file-formats

- Does MapMap currently play the audio of the files?
- Should we add more containers? (file extensions) Which ones?

**Comment by sofian** [comment]
1. Yes audio is supported now. It has been tested on Ubuntu.
2. For codecs: QuickTime Animation (RLE) is what I used to produce videos that support transparency.
Also we should mention animated GIFs support cause it's so cool.
