### ISSUE TITLE
OSC is not supported on MacOS

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#283]
We should link to liblo. 

Maybe that can help us: http://www.learnopencv.com/configuring-qt-for-opencv-on-osx/

**Comment by aalex** [comment]
Will be fixed by #339

**Comment by minusplusminus** [comment]
Could at least the person be informed about this issue in the UI?

**Comment by aalex** [comment]
Good idea!

**Comment by aalex** [comment]
213786465a2066085a90674e95c4e7fd985632ac
