### ISSUE TITLE
Window is not maximizable (Linux)

### ISSUE THREAD

**Issue by nodiscc** [mapmapteam/mapmap#286]
Hi, running XFCE/XFWM4, mapmap's window maximize control does not work.

**Comment by sofian** [comment]
Are you talking about the fullscreen mode or really the maximize control in the top-left corner?

**Comment by nodiscc** [comment]
the maximize control in the top-left corner. I expected it to maximize mapmap's window.

**Comment by EmerickH** [comment]
Have you tried Alt+F5?
It seems to be the default shorcut in XFCE: http://www.knuckleheadtech.com/xfce4-keyboard-shortcuts/

Emerick

**Comment by nodiscc** [comment]
@EmerickH @sofian I've just tried using other window manager functionality (Alt+F5, or window menu > Maximize) and none of them work.

**Comment by redraw** [comment]
still not maximizable!
