### ISSUE TITLE
Is spacebar a good idea for pause/play hotkey?

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#292]
Currently spacebar is used for pausing and playing MapMap. But I am not sure it is such a good idea. Here is why I think so.

* Spacebar is the biggest key on the keyboard. Therefore it is super easy to press... and even press by mistake
* Play/pause is not an action you will do *that* often when using MapMap. In general you'll build everything while the software is running.
* However, when your piece is running, pausing the system by mistake can be *really bad* (imagine you are on stage in front of 1000 people and everything just stops).

I think we should replace the play/pause action by a more secure hotkey (one that requires a combination of two keys, maybe CTRL-spacebar?) What do you think?

**Comment by aalex** [comment]
Pausing is not very useful at all. Let's remove that shortcut. No shortcut required, or pick Ctrl-Shift-P, or so.
