### ISSUE TITLE
It crashes when duplicating a mapping

### ISSUE THREAD

**Issue by ferhoyo** [mapmapteam/mapmap#298]
It crashes when duplicating a mapping with more than 4 points.
To recreate the chash:
Select a mesh
In Property --> Dimensions, increase the width or height (creating more points)
Duplicate the mapping
This creates a mapping with points loose (not attached with lines to the rest),
if you try to move one of this loose points... it crashes #

This happens with version 0.4.1
Compiled in Ubuntu 16.04 64bit

Previous version 0.4.0 it also crashed when duplicating mappings with more than 4 points. This was with Ubuntu 14.04 and also with Windows 10

**Comment by sofian** [comment]
Thanks, fixed it in the develop branch.
