### ISSUE TITLE
Not packaged for Ubuntu 16.04

### ISSUE THREAD

**Issue by EmerickH** [mapmapteam/mapmap#300]
Hello,
I'm trying to install MapMap on Ubuntu 16.04 but there's a problem:
I did:

> emerick@EMERICK-PC-Ubuntu:/etc/apt/sources.list.d$ sudo add-apt-repository ppa:mapmap/mapmap
>  MapMap is a free/open source video mapping software.
> 
> sudo apt-add-repository -y ppa:mapmap/mapmap
> sudo apt-get update
> sudo apt-get install -y mapmap
>  Plus d’info : https://launchpad.net/~mapmap/+archive/ubuntu/mapmap
> Appuyez sur [ENTRÉE] pour continuer ou Ctrl-C pour annuler l’ajout
> 
> gpg: le porte-clefs « /tmp/tmprk1_qo8u/secring.gpg » a été créé
> gpg: le porte-clefs « /tmp/tmprk1_qo8u/pubring.gpg » a été créé
> gpg: demande de la clef EF69F649 sur le serveur hkp keyserver.ubuntu.com
> gpg: /tmp/tmprk1_qo8u/trustdb.gpg : base de confiance créée
> gpg: clef EF69F649 : clef publique « Launchpad PPA for MapMap » importée
> gpg: Quantité totale traitée : 1
> gpg:               importées : 1  (RSA: 1)
> OK
> 

But when I do apt-get update:

> Ign:6 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 Packages                
> Ign:7 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main i386 Packages 
> Réception de:8 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]             
> Ign:9 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main all Packages  
> Ign:10 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr_FR
> Ign:11 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr
> Ign:12 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-en
> Ign:13 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 DEP-11 Metadata
> Ign:14 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main DEP-11 64x64 Icons
> Ign:6 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 Packages
> Ign:7 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main i386 Packages
> Ign:9 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main all Packages
> Ign:10 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr_FR
> Ign:11 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr
> Ign:12 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-en
> Ign:13 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 DEP-11 Metadata
> Ign:14 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main DEP-11 64x64 Icons
> Ign:6 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 Packages
> Ign:7 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main i386 Packages
> Ign:9 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main all Packages
> Ign:10 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr_FR
> Ign:11 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr
> Ign:12 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-en
> Ign:13 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 DEP-11 Metadata
> Ign:14 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main DEP-11 64x64 Icons
> Ign:6 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 Packages
> Ign:7 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main i386 Packages
> Ign:9 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main all Packages
> Ign:10 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr_FR
> Ign:11 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr
> Ign:12 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-en
> Ign:13 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 DEP-11 Metadata
> Ign:14 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main DEP-11 64x64 Icons
> Ign:6 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 Packages
> Ign:7 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main i386 Packages
> Ign:9 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main all Packages
> Ign:10 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr_FR
> Ign:11 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr
> Ign:12 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-en
> Ign:13 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 DEP-11 Metadata
> Ign:14 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main DEP-11 64x64 Icons
> Err:6 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 Packages
>   404  Not Found
> Err:7 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main i386 Packages
>   404  Not Found
> Ign:9 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main all Packages
> Ign:10 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr_FR
> Ign:11 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-fr
> Ign:12 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main Translation-en
> Ign:13 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main amd64 DEP-11 Metadata
> Ign:14 http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial/main DEP-11 64x64 Icons
> 102 ko réceptionnés en 2s (35,6 ko/s)
> Lecture des listes de paquets... Fait
> W: The repository 'http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main xenial Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Impossible de récupérer http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main/dists/xenial/main/binary-amd64/Packages  404  Not Found
> E: Impossible de récupérer http://ppa.launchpad.net/mapmap/mapmap/ubuntu/dists/trusty/main/dists/xenial/main/binary-i386/Packages  404  Not Found
> E: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.

I tried to compile manually but I did not succeed (I don't know how to do: I've downloaded all dependencies but I've got only error messages when I start build.sh).

Thanks,
Emerick

**Comment by sofian** [comment]
@aalex Do you know what is going on?

**Comment by aalex** [comment]
MapMap is not packaged for Xenial yet.

**Comment by EmerickH** [comment]
Ok thank you,
When will it be compiled?

Emerick

**Comment by aalex** [comment]
Good question! I might have some time for a sprint on December 10th or
11th. I also accept donations, to speed this up.

**Comment by EmerickH** [comment]
Ok, I was finally able to compile with QtCreator 5 because it don't want to compile with build.sh on Ubuntu 16.04, same thing with Qt4 or Qt5 (log says "error: QtWidgets: No such file or directory").

Emerick

**Comment by aalex** [comment]
Here are the Ubuntu packages for each part of Qt. 

Qt module           dev package                         lib package
-------------------------------------------------------------------------
bluetooth           qtconnectivity5-dev                 libqt5bluetooth5
concurrent          qtbase5-dev                         libqt5concurrent5
connectivity        qtmobility-dev                      libqtconnectivity1
contacts            qtmobility-dev                      libqt5contacts5
core                qtbase5-dev                         libqt5core5a
dbus                qtbase5-dev                         libqt5dbus5
designer            qttools5-dev                        libqt5designer5
designercomponents  qttools5-dev                        libqt5designercomponents5
feedback            qtmobility-dev                      libqt5feedback5
gallery             qtmobility-dev                      libqtgallery1
gui                 qtbase5-dev                         libqt5gui5
help                qttools5-dev                        libqt5help5
location            qtmobility-dev                      libqt5location5
multimedia          qtmultimedia5-dev                   libqt5multimedia5
multimediakit       qtmobility-dev                      libqtmultimediakit1
network             qtbase5-dev                         libqt5network5
nfc                 qtconnectivity5-dev                 libqt5nfc5
opengl              libqt5opengl5-dev                   libqt5opengl5
organizer           qtmobility-dev                      libqt5organizer5
positioning         qtpositioning5-dev                  libqt5positioning5
printsupport        qtbase5-dev                         libqt5printsupport5
publishsubscribe    qtmobility-dev                      libqt5publishsubscribe5
qml                 qtdeclarative5-dev                  libqt5qml5
quick               qtdeclarative5-dev                  libqt5quick5
quickparticles      qtdeclarative5-dev                  libqt5quickparticles5
quicktest           qtdeclarative5-dev                  libqt5quicktest5
quickwidgets        qtdeclarative5-dev                  libqt5quickwidgets5
script              qtscript5-dev                       libqt5script5
scripttools         qtscript5-dev                       libqt5scripttools5
sensors             qtmobility-dev, libqt5sensors5-dev  libqt5sensors5
serialport          libqt5serialport5-dev               libqt5serialport5
serviceframework    qtmobility-dev                      libqt5serviceframework5
sql                 qtbase5-dev                         libqt5sql5
svg                 libqt5svg5-dev                      libqt5svg5
systeminfo          qtmobility-dev                      libqt5systeminfo5
test                qtbase5-dev                         libqt5test5
uitools             qttools5-dev                        ?
versit              qtmobility-dev                      libqtversit1
webchannel          ?                                   ?
webkit              libqt5webkit5-dev                   libqt5webkit5
websockets          libqt5websockets5-dev               libqt5websockets5
widgets             qtbase5-dev                         libqt5widgets5
x11extras           libqt5x11extras5-dev                libqt5x11extras5
xml                 qtbase5-dev                         libqt5xml5
xmlpatterns         libqt5xmlpatterns5-dev              libqt5xmlpatterns5

**Comment by aalex** [comment]
It's now packaged for 16.04 on Launchpad.
