### ISSUE TITLE
Not starting on Windows

### ISSUE THREAD

**Issue by EmerickH** [mapmapteam/mapmap#301]
On my Windows 10, MapMap installs correctly but when I open it, nothing appends.

**Comment by aalex** [comment]
Make sure you installed GStreamer and its plugins.

**Comment by aalex** [comment]
Can you provide a screenshot or more details?

**Comment by EmerickH** [comment]
I've debugged MapMap.exe with Visual Studio, the problem seems to be with Qt:
![1](https://cloud.githubusercontent.com/assets/21125429/22242012/0ab6efb2-e222-11e6-9e33-ab2f1de22151.PNG)
I have a lot of message like this, if you don't speak french:
> Exception thrown at 0x6195C34F (Qt5Gui.dll) in Mapmap.exe: 0xC0000005: Access Violation when reading location 0x00000000.

**Comment by EmerickH** [comment]
And I forgot to precise: I've installed it from the installer:
http://download.mapmap.info/windows/

**Comment by EmerickH** [comment]
I found a solution!
Just start MapMap in Windows XP compatibility mode and it will work!

**Comment by sofian** [comment]
Great!
