### ISSUE TITLE
The script that generates contributors is inconsistent

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#303]
The script ```scripts/update-contributors.sh``` which creates ```docs/informations/CONTRIBUTORS.html``` that is available through the "About" dialog is inconsistent. There are duplicates, old email adresses, nicknames, etc.

I like the idea of automation but I feel like this one is a bit "rough". Maybe we should generate it by hand?

**Comment by aalex** [comment]
Wow. Github l'a fermé automatiquement. :)
