### ISSUE TITLE
Too many menus

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#305]
There are currently 7 menus in MapMap on Ubuntu 16.04. This number if pretty high and could be reduced.

* Put the only item under the "Tools" menus into the "Window" menu. "Window > Open console"
* Rename the "Output" menu to "View"
* Move the items under "Playback" as a menu item of "View". "View > Playback > Pause" and "View > Playback > Rewind"

**Comment by sofian** [comment]
I agree with the following:
* Put the only item under the "Tools" menus into the "Window" menu. "Window > Open console"
* Rename the "Output" menu to "View"

However for "Playback" I would not put it as a submenu of "View" but rather put directly the Pause and Rewind items in the View menu, with a separator.

**Comment by sofian** [comment]
Cause there's also too many submenus imho.

**Comment by sofian** [comment]
Like in "Window > Toolbars > Toolbar", we should remove the submenu "Toolbars" for now until we actually really have many toolbars.

**Comment by sofian** [comment]
Ok I've rearranged everything in the View menu. @aalex Check out the fix_305_merge_menus branch and let me know what you think.

**Comment by aalex** [comment]
wow! that looks good
