### ISSUE TITLE
Windows 0.4 and 0.5 install files possibly infected

### ISSUE THREAD

**Issue by dk67** [mapmapteam/mapmap#317]
bonjour,
Avast me signale une infection par Filerepmalware des fichiers d'installation windows....
Cordialement

**Comment by MrWu-at-msv** [comment]
Hi got same problems, on moth versions: 0.4 and 0.5
Meme problème avec les deux version: 0.4 et 0.5

**Comment by sofian** [comment]
All right, thanks, we'll investigate.
I've removed the files from the server for now.

**Comment by sofian** [comment]
I have removed the files from the server for now. We will look into this.

**Comment by sofian** [comment]
We believe these are probably false positives.
According to these tests, only 1 / 56 antiviruses detected something in the installers, and in both cases it was a different one.

https://www.virustotal.com/en/file/589058de3dd17f1d951c4ecae63ef63f12018e3146be908843a5456b09b3bb28/analysis/
https://www.virustotal.com/en/file/10321b423acf102e761895f8bae591457a0511a61cd2d1b74f7b7f027d8175ce/analysis/

**Comment by sofian** [comment]
Still we'll pursue our investigations to make sure not to put anyone at risk.

**Comment by baydam** [comment]
This issue can be close now
