### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by skankerror** [mapmapteam/mapmap#318]
On archlinux (manjaro) 64bit I have a segfault with last sources. Don't know how to compile with debug option ?

**Comment by aalex** [comment]
Where does the segfault occur? Any traceback or message in a terminal?
Simply run "mapmap" in a terminal.

**Comment by skankerror** [comment]
[ray@raymanjaro_toshiba mapmap]$ ./mapmap 
Erreur de segmentation (core dumped)

**Comment by sofian** [comment]
Can you send the core dump?

**Comment by skankerror** [comment]
can you explain me how to send the core dump please ?

**Comment by sofian** [comment]
Sorry.
There should be a file called "core" in the same directory from which you ran mapmap.
Maybe there isn't, but if there is, please send it to us to info@mapmap.info
Thanks.

**Comment by skankerror** [comment]
Sorry no file called core...

**Comment by sofian** [comment]
All right, that's because the distributed version of the program was compiled without debugging flags.
Could you try running the program using GDB:
$ gdb ./mapmap

When the prompt comes, just type:
r

This will start the program. It will crash. Then type:
bt

This will print a backtrace which you can send us. This would help us in understanding where the program failed.

**Comment by skankerror** [comment]
Ok, here's backtrace :


(gdb) r
Starting program: /home/ray/src/mapmap/mapmap
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe87c1700 (LWP 2719)]

Thread 1 "mapmap" received signal SIGSEGV, Segmentation fault.
0x00007ffff6062ed4 in QCommonStyle::pixelMetric(QStyle::PixelMetric, 
QStyleOption const*, QWidget const*) const () from 
/usr/lib/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff6062ed4 in QCommonStyle::pixelMetric(QStyle::PixelMetric, 
QStyleOption const*, QWidget const*) const () at /usr/lib/libQt5Widgets.so.5
#1  0x00007ffff61af9db in QWidgetTextControl::setCursorWidth(int) ()
     at /usr/lib/libQt5Widgets.so.5
#2  0x00007ffff61afa9d in 
QWidgetTextControl::QWidgetTextControl(QObject*) ()
     at /usr/lib/libQt5Widgets.so.5
#3  0x00007ffff61c94a1 in  () at /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff61ca060 in  () at /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff61ca6b0 in QPlainTextEdit::QPlainTextEdit(QWidget*) ()
     at /usr/lib/libQt5Widgets.so.5
#6  0x0000000000433aa0 in mmp::ConsoleWindow::ConsoleWindow(QWidget*) 
(this=0x95bca0, parent=0x0) at ConsoleWindow.cpp:33
#7  0x0000000000433e10 in mmp::ConsoleWindow::console() ()
     at ConsoleWindow.cpp:63
#8  0x000000000049eca6 in logMessageHandler(QtMsgType, 
QMessageLogContext const&, QString const&) (type=QtDebugMsg, 
context=..., msg=...) at main.cpp:73
#9  0x00007ffff486daee in qt_message_output(QtMsgType, 
QMessageLogContext const&, QString const&) () at /usr/lib/libQt5Core.so.5
#10 0x00007ffff4973950 in QDebug::~QDebug() () at /usr/lib/libQt5Core.so.5
#11 0x00007fffe734a81d in Qt5CTPlatformTheme::Qt5CTPlatformTheme() ()
     at /usr/lib/qt/plugins/platformthemes/libqt5ct.so
#12 0x00007fffe7347600 in Qt5CTPlatformThemePlugin::create(QString 
const&, QStringList const&) () at 
/usr/lib/qt/plugins/platformthemes/libqt5ct.so
---Type <return> to continue, or q <return> to quit---
#13 0x00007ffff5538c62 in  () at /usr/lib/libQt5Gui.so.5
#14 0x00007ffff5543788 in 
QGuiApplicationPrivate::createPlatformIntegration() () at 
/usr/lib/libQt5Gui.so.5
#15 0x00007ffff554418d in 
QGuiApplicationPrivate::createEventDispatcher() () at 
/usr/lib/libQt5Gui.so.5
#16 0x00007ffff4a6802f in QCoreApplicationPrivate::init() () at 
/usr/lib/libQt5Core.so.5
#17 0x00007ffff5545baf in QGuiApplicationPrivate::init() () at 
/usr/lib/libQt5Gui.so.5
#18 0x00007ffff5ff1009 in QApplicationPrivate::init() () at 
/usr/lib/libQt5Widgets.so.5
#19 0x00000000004386ae in mmp::MainApplication::MainApplication(int&, 
char**) (this=0x7fffffffd580, argc=@0x7fffffffd3fc: 1, 
argv=0x7fffffffdc48) at MainApplication.cpp:27
#20 0x000000000049ed18 in main(int, char**) (argc=1, 
argv=0x7fffffffdc48) at main.cpp:86

**Comment by sofian** [comment]
Thanks. The crash happens on Qt side, which makes it very hard for me to debug without access to the system.

Have you tried compiling by yourself?

**Comment by skankerror** [comment]
Yes I compiled. But I just realise that my qt5-multimedia and qt5-tools 
packages are still 5.7 version. I'm fixing this, then will recompile the 
app. Is there a way to compile with debug flags ?

**Comment by sofian** [comment]
Yes, just edit the mapmap.pro file and add "debug" to the CONFIG flags. eg.
```CONFIG  += qt debug c++11```

**Comment by skankerror** [comment]
Finally upgrading to qt5.8 solved this issue.
