### ISSUE TITLE
The "liblo-dev" package doesn't provide "osc-send" command anymore on Debian

### ISSUE THREAD

**Issue by baydam** [mapmapteam/mapmap#328]

**Comment by baydam** [comment]
We need to install "liblo-tools" package separately to have command line tools

**Comment by aalex** [comment]
I most often use python-txosc, my own tool. It contains osc-send and osc-receive. The tools in liblo-tools are named oscsend and oscreceive. These are different tools. (they are faster and should be slightly more reliable)

**Comment by baydam** [comment]
If it is really easy to install on most operating system maybe we can put it on INSTALL instruction file intstead

**Comment by aalex** [comment]
Which one is really easy to install?
