### ISSUE TITLE
Crash when sending OSC from the Processing example sketch

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#343]
Just another problem, I tried to change processing_mapmap to get it work : mapmapteam/processing-mapmap#1
And guess what ? mapmap crashes when I press 's', with first osc receive. Did I make something wrong ?

@skankerror

**Comment by skankerror** [comment]
I made a pull request with working changes in processing-mapmap.

**Comment by sofian** [comment]
Thanks @skankerror ! I merged your changes.
