### ISSUE TITLE
Verify the type of our timers

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#345]
By default, Qtimer::timerType is Qt::CoarseTimer. (5% accurate) Sometimes, we might want to use Qt::PreciseTimer. (1 ms accurate)

**Comment by sofian** [comment]
This is something that could be offered as an adjustment in the preferences.

**Comment by aalex** [comment]
There seems to be only two timers right now:
- MainWindow::videoTimer: interval/frequency is 29.97 Hz by default for videoTimer. Precision is Qt::CoarseTimer. (5% accurate) We might prefer Qt::PreciseTimer for that one.
- MainWindow::osc_timer: An interval of 0 will time out as soon as all the events in the window system's event queue have been processed. We might leave that one as a Qt::CoarseTimer.

**Comment by sofian** [comment]
+1 to what you suggest
