### ISSUE TITLE
MapMap lags indefinitely on macOS when importing a video

### ISSUE THREAD

**Issue by sofian** [mapmapteam/mapmap#373]
This is the error that I am getting:

```
0:00:14.096434000   608 0x7f8780319f80 WARN            uridecodebin gsturidecodebin.c:1388:GstElement *gen_source_element(GstURIDecodeBin *):<uridecodebin0> error: No URI specified to play from.
```

I guess it has to do with some URI format for the file (?)

**Comment by sofian** [comment]
I am on macOS 10.9.5.

**Comment by aalex** [comment]
Use gst-inspect to see if the playbin has a uri property. Next, see if we
set its value in our code.

**Comment by sofian** [comment]
I was able to fix this. I am not exactly sure how because I did many things:
* Pretty sure this is what fixed it: sudo chmod -R 755 /Library/Frameworks/GStreamer.framework
* Also I installed missing packages using HomeBrew: brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav
