### ISSUE TITLE
Spike: video playback with QtMultimedia

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#379]
In the spike that @sofian did, there is a lag in the looping.
There is a branch that lies in the repository: feature/qtmultimedia
We need to fix that lag in the looping.

**Comment by sofian** [comment]
@baydam Just tried your branch feature/qtmultimedia and it works. However there is a bug : MapMap crashes (Segfault) when I try to add a 2nd video.

**Comment by baydam** [comment]
Wow I gonna check this! Thanks

**Comment by sofian** [comment]
I tried the feature/qtmultimedia branch on both Linux and MacOS and it works! However there are a few bugs.

**Comment by aalex** [comment]
See #299 for the spike backlog item.
