### ISSUE TITLE
Ctrl-Q should quit the application

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#40]

**Comment by aalex** [comment]
If it works for you doesn't mean it works for everyone. It doesn't work here. (Ubuntu 14.04) It haven't worked on most - if not all - setups I have witnessed. Please let me close this issue when I will have verified it's fixed. Also, it's a good practice to add a comment stating in which commit number it has been fixed before closing the issue.

**Comment by baydam** [comment]
Yep

@bay_dam
