### ISSUE TITLE
Support drag and drop for video files

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#409]
As a user, I want to be able to simply drag & drop a file into the Library pane in order to load a new media file.

https://wiki.qt.io/Drag_and_Drop_of_files

**Comment by matthewloe** [comment]
Also add the ability to import folders along with media files. As a user who needs to import a lot to the library I do not want to have to import each media file separate.

**Comment by baydam** [comment]
@aalex @matthewloe Are you already try to drag and drop project file or videos to any surface of the MapMap windows? 
Because this already exists on MapMap. You can drag and drop many media files

**Comment by baydam** [comment]
Feel free to close this issue if it is work for you

**Comment by jabland** [comment]
On macOS you can't drag and drop into the program

**Comment by aalex** [comment]
It should probably be changed to a bug, then. (to be verified)

**Comment by aalex** [comment]
It works.
