### ISSUE TITLE
[linux][build] project error : unknown module qtmultimedia

### ISSUE THREAD

**Issue by Olm-e** [mapmapteam/mapmap#431]
hello,
building on linux mint 18.3 (=  base ubuntu 16.04) qmake finish with
"...
Project MESSAGE: MapMap version: 0.6.2
Project ERROR: Unknown module(s) in QT: multimedia"

and cannot create the makefile ...

some leftover from the qtmultimedia branch ? 

[edit] does the same on master 0.6.1 branch

**Comment by aalex** [comment]
`sudo apt-get install qtmultimedia5-dev libqt5multimedia5-plugins` ?

**Comment by Olm-e** [comment]
ok, qmake can build the makefile with those libs (could'nt find them by reverse... synaptic nor apt shown them obviously ;) )

then you also need libqt5opengl5 and libqt5opengl5-dev to build (to add in the install.md )
and then it works :D 

(and cheers from Bxl ;) )
