### ISSUE TITLE
Missing DLL files on Windows

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#442]
"I´m having some .dll problems while loading the software. can anybody help? 
Missing Files: libopenh264.dll, libsoundtouch-1.dll, libstdc++-6.dll "

<img width="536" alt="capture d ecran 2018-08-21 a 13 58 34" src="https://user-images.githubusercontent.com/293677/44419875-5b234080-a54a-11e8-9540-b59a26968138.png">

**Comment by shadypark** [comment]
any movement on this issue?

**Comment by JadnarRoverdin** [comment]
Would like to add, Just received this error on a fresh install on Windows 8.1. All three were reported as missing from my system. Thank you!

**Comment by OmiPops** [comment]
Me too. Windows 7 64-bit. And several other library files too (libSoundTouch-1, entry point gxx-personality-sj0, ...)

**Comment by baydam** [comment]
Hello, did you try the last version?
http://download.mapmap.info/windows/mapmap-0.6.3-x86-installer.exe

**Comment by OmiPops** [comment]
Thanks a lot - that fixed my problem !

**Comment by JadnarRoverdin** [comment]
Had recently done a clean install of Windows 8.1. I installed your linked version today. No errors on startup. Thank you @baydam.

**Comment by sofian** [comment]
The new version seems to have fixed it.

**Comment by Darrel-Collinsworth** [comment]
download link is borken
