### ISSUE TITLE
problem to open camera device

### ISSUE THREAD

**Issue by Laurentiz** [mapmapteam/mapmap#452]
when I try to open Camera Device I get the message:  
Cannot read file @device:pnp://?/....

![error](https://user-images.githubusercontent.com/44985699/48379693-30b1d100-e6bc-11e8-95e3-84d10bc90699.jpg)

**Comment by aalex** [comment]
On which OS is this? Which version of MapMap?

**Comment by sofian** [comment]
Closing due to lack of information.
