### ISSUE TITLE
MapMap 0.5.0

### ISSUE THREAD

**Issue by arrowhead09** [mapmapteam/mapmap#460]
Using MapMap 0.5.0 on Windows 10, I'm unable to see the Source option under Property of any media file that I add.  I have a Benq projector connected to my computer.  Is there a workaround to get the Source option in the Property of the media files?  Thanks.

Arrowhead09

**Comment by baydam** [comment]
Hi, Are you able to see any properties under de Layer panel. if yes you maybe have to dis-collapse your Source properties panel or check your screen resolution.

**Comment by arrowhead09** [comment]
Hi Baydam,,

Under the Property layer it has Paint and under that I can see Opacity, Video File (i can change the file), Speed, and Volume.  Under the Property panel for . png file I imported, I can see Opacity, ImageFile (which I can change) and Speed.  After I click on the Plus rectangle (Mesh), I see Mapping with only Opacity, Dimensions, Input Shape, and Output Shape.  I don't know why I'm not seeing Source.  My screen resolution is 2556x1440.  Am I missing something very basic?  Thanks.

**Comment by arrowhead09** [comment]
Nvm.  I installed the latest version (0.6.4) and I'm now able to see Source.  Thank you.

**Comment by lilyCalla** [comment]
@arrowhead09 Can you close this issue?
