### ISSUE TITLE
Mapmap website down & repo activity

### ISSUE THREAD

**Issue by diroots** [mapmapteam/mapmap#462]
hello mapmap team. 

Do you know your website is down? 

Also, how is actually doing on the mapmap project? as we can see no new commit on the repo since march... are you still working on this tool? is there a next release coming? far from now or pretty soon?

**Comment by aalex** [comment]
Hello,
There will be some activity this summer, for sure.

The website mapmap.info has been taken down.
The official site is now mapmapteam.github.io
Any help would be quite welcome.
Best,

**Comment by EmerickH** [comment]
@aalex if you need some help on the website I can help you, I can even host it on my VPS for free if you want (as I've not money it will be my donation to MapMap project :wink:)

**Comment by diroots** [comment]
Ok good news, thanks. 

I'm actually using mapmap on some mapping installations, and while using it, I get some strange behaviors. 

for example,  when having loaded medias in sources, set up some layers using these different medias, if, after this first setup, I want to load new medias in the library (so I can switch in the already defined layers) many of the defined layers suddenly switch to a default source, and I can not anymore switch back to any of the sources of my library on these layers. I need to recreate layers to be able to use any of the source. 

Is there a way of switching to debug mode, to be able to send you some informations I can have for you to better understand things I could present? I tried to find out some informations from the command line to get an eventual message when thez above error happens, but, I only get general messages, nothing useful (I think)

mapmap 0.6.2 on debian 9

**Comment by aalex** [comment]
@EmerickH I think what would be quite useful are build servers! Either macOS, Windows or Ubuntu. For the web site, the GitHub Pages do the trick, for now, I think.

**Comment by aalex** [comment]
@diroots You should probably open another GitHub issue for the problems you describe.

**Comment by EmerickH** [comment]
@aalex Ok I can maybe help you with that, I have not so much time actually but I will check when I can how I can automate this on my VPS. Just by curiosity, what's the problem with Travis and Appveyor?
What about OpenSUSE build servers for Linux?
https://build.opensuse.org/

**Comment by sofian** [comment]
I will close this issue for now because the website is currently up and running.
