### ISSUE TITLE
OSC support on Windows + Processing example

### ISSUE THREAD

**Issue by robertoboote** [mapmapteam/mapmap#466]
Hola MapMapteam! prodrían hacer un ejemplo para usar osc y processing en windows, en especial ajustando la opacidad o haciendo visible una o mas capas? muchas gracias!

**Comment by aalex** [comment]
Hola!
No es posible ya, pero seria muy facil de cambiar el codigo de MapMap para hacerlo.
Tengo el codigo para hacerlo, pero no tengo mucho tiempo estos dias. 
Estar pagado para hacerlo seria un buen razon de hacerlo pronto.
Gracias!

**Comment by robertoboote** [comment]
Hola! tu dices que es posible cambiar el codigo para utilizar OSC y processing? las modificaciones serian  efectivas para todas las ordenes? Cuanto podría costar eso y en que tiempo podrias hacerlo? Muchas gracias! por contestar tan atentamente!!!

**Comment by aalex** [comment]
Por favor escribeme a quessy@gmail.com 

Si: seria posible!
