### ISSUE TITLE
Freezes since commit 202599637075b581800feff5714c75c3530c3ec1

### ISSUE THREAD

**Issue by skankerror** [mapmapteam/mapmap#469]
since this commit : https://github.com/mapmapteam/mapmap/commit/202599637075b581800feff5714c75c3530c3ec1 I'm not able to run my projects without freezing, especially when I send osc message for change opacity in some seconds, and when I make croosfades of opacity. Mapmap freezes for some seconds, being unable to process transitions.
I tried on several computer on linux, even with strongs graphic cards.

**Comment by sofian** [comment]
Thanks for the report. The commit does some kind of checking during property assignments/modifications which would resonate with the problem you are reporting. There might be some kind of bottleneck (object creation, recursion, ...) that happens. I am not quite able to see what it could be just by looking at the code but I could troubleshoot. It likely has nothing to do with your graphics card.

Can you post instructions on how to reproduce the error?

**Comment by skankerror** [comment]
Go on this ggdrive : https://drive.google.com/open?id=1iJeK_Bskvi2SPSmjerzC1wZbaOw6Nz6v
Create a new project and import several media from these, create a rect mesh per one

Now go on this link : https://drive.google.com/open?id=1P30VxZUDR0o2iLssYgLITrzvMBAHIXkG
You'll find scripts for oscsend. Get opacity_mapmap_up.sh and opacity_mapmap_down.sh

With these scripts try a crossfade for example
$ opacity_mapmap_up.sh 1 9 &
$ opacity_mapmap_down.sh 2 7

Here are screen recording of what happens with my projects :
With git version : https://drive.google.com/open?id=1aD0H2HLpACZm-4hQKNKNXxsOygMypVXm
With 0.5 release : https://drive.google.com/open?id=1ULavuZV9H04MXAkfUepf7I7kkAZpM89M

You have all the files for the project and the scripts commanding it in drives link

**Comment by skankerror** [comment]
I looked commit by commit between 0.5 and 0.6 to see what happened, that's how I discovered this commit

**Comment by sofian** [comment]
Thanks, this will be very useful. I will look into this as soon as I can.
BTW in the future, you might be interested in using ```git bisect``` to discover harmful commits: it is by far my favorite feature of git!

**Comment by sofian** [comment]
Just made some changes: Can you give it a try with commit e2aa49c?

**Comment by skankerror** [comment]
It solved the problem !
Thanks a lot

**Comment by sofian** [comment]
Glad to hear!
