### ISSUE TITLE
Issue with source rate

### ISSUE THREAD

**Issue by skankerror** [mapmapteam/mapmap#476]
Hi guys

when setting rate at negative I expect video source to play in reverse loop when "play in loop" is set at playback preferences. But video actually pauses when it comes to the beginning.
Another problem, it seems that https://github.com/mapmapteam/mapmap/issues/369 is back. When setting rate at, for example 200%, it turns back to 100% after loop.

Last develop version on linux manjaro.

**Comment by sofian** [comment]
This is a known issue #216 it is quite hard to fix so we have decided to put it aside for now.
I will reopen #369. It would accelerate things if you were able to identify which commit caused the bug to appear.

**Comment by skankerror** [comment]
Ok, I didn't see #216 , I'll try to bisect this #369 bug
