### ISSUE TITLE
A way to copy verticles datas from a layer to another existing one

### ISSUE THREAD

**Issue by skankerror** [mapmapteam/mapmap#477]
For this project : https://drive.google.com/open?id=11ymLD_Prm0C7heLwRmX4nMpzfU68rmdT I have four layers with exactly same vertices (id 1, 2, 9, 12, for transitions needs). When the show plays at a new place I remap one layer to conditions of local stage set. Then I edit the xml project by copying vertices section of this layer to three others layers.

A way inside app to copy these vertices to others layers would be easier, faster and safer.

I know I can create new layer by copying existing one, but here I have still my layers.

Of course I can continue handle this the way I do.

**Comment by sofian** [comment]
I guess the "duplicate" action should put the copied item directly on top of the previous one instead of the current situation. What is your opinion on this @baydam and @aalex ?

**Comment by sofian** [comment]
Fixed in develop branch: duplicate items now appear directly on top of previous one.
