### ISSUE TITLE
New to all this and have some problems.

### ISSUE THREAD

**Issue by LeeRoyy12345** [mapmapteam/mapmap#515]
I installed mapmap and it worked on my pc
I am  having problems with using extended screen with my pc/projector if I mirror they work but if I extend it as it said I either get just my background pic on my pc and taskbar on bottom but nothing else and vise/versa.

Then the mapping since I cant figure out how to get the screen right its a problem.
So I just went back to mirroring went full screen and just moved the item around that way till I got it the size and spot I wanted it to be.

Once I did all that I wanted to save it to see if it was right and it saved it I named it as test1 so it saved it as test1.mmp I think.
Now I decided to test it out and play it so I went to open file and I seen it in the location it was a blank page icon that said test1.mmp so I clicked on it and opened it and it brought up a black screen with the circles with the + in to move it around and nothing else then it booted me out of the program and the angel wings popped up saying it crashed and now I cant do anything but start all over.

Any help for me?
Thanks in advance.

Edit. Update. So I tried it again as soon as I try to open a new image it crashes as soon as I add a new layer using the square layer.
So I tried it again this time instead of the square layer I used the triangle layer it popped up and started working on the color triangle on the output screen but it wasnt showing anything on the top screen so I removed the color and tried it and next thing I know it crashed. So I tried it again with the circle layer and it crashed as soon as I picked it.

**Comment by LeeRoyy12345** [comment]
What a useless site...

**Comment by aalex** [comment]
Hello @LeeRoyy12345 ! Thank you for your bug report. If you could include some images, and mention exactly which version of MapMap and which operating system, it would help us to help you. MapMap is an open source software, and we currently have not much funding, so it's normal if there is not much response to your queries. Perhaps what you could do is add more info - or make the info easier to read for the other users and developers. You can also hire one of the developers - for example by contacting me at http://quessy.net - for more help. 

Best regards.

**Comment by LeeRoyy12345** [comment]
I think I figured out a solution on my own... I downloaded the newest version and it would work then crash so I decided to also download the next older version as well and since then it has not crashed... so I had the files for the latest version and the files for the next to the latest version....
