### ISSUE TITLE
Delete deprecated branches in the Git repository

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#73]

**Comment by aalex** [comment]
They are listed here:
https://github.com/mapmapteam/mapmap/branches/stale?page=1
https://github.com/mapmapteam/mapmap/branches/stale?page=2
(except branch 0.1, which is a major.minor branch)

**Comment by baydam** [comment]
La plupart d'entre elles ont été créé par vous et Sofian mais je pourrais m'en charger 

@bay_dam

**Comment by aalex** [comment]
Non non c'est bon: merci!

**Comment by aalex** [comment]
I moved the following branches to https://github.com/mapmapteam/mapmap-old-branches : statesaving ellipseshape output-window remove-paints-mappings multi-image-loop-texture spike-video-drone gst-osx qt5-linux fix-video-not-displaying gui-controls-refactor mike-style-integration osx-fixes osx-fails osx-fix-june-2014 develop-rebase-fix-osx-june-2014 play-pause-rewind menu-toolbar-qaction-different-qicon mire feature-refactor-gui-organization feature-merge-vliaskov-shmsrcbin feature-zoom-and-scroll bugfix-video-memory-leaks bugfix-refactor-mediaimpl spike-layer-property-editor
