### ISSUE TITLE
The saved window settings prevents the correct display of new features

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#78]
Often, you won't see the new features, since the window appearance that was saved in your settings doesn't include them.

For example, the propertybrowser for a paint or mapping doesn't appear if one has used a previous version of MapMap on a given computer account.

Erasing the settings file should work. Launch MapMap from the command-line with the --reset-settings option fixes it.

Maybe we should simply reset the settings each time they are not backward-compatible. (by saving the version number in the settings)

**Comment by baydam** [comment]
This issues can be closed because we do like this way https://github.com/mapmapteam/mapmap/blob/develop/MainWindow.cpp#L2030
