### ISSUE TITLE
The uninstall rule tries to remove system directories

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#90]
sudo LANG=C make uninstall
Makefile:406: warning: overriding commands for target `docs'
Makefile:403: warning: ignoring old commands for target `docs'
rm -f -r /usr/bin/mapmap
rmdir /usr/bin/ 
rmdir: failed to remove '/usr/bin/': Directory not empty
make: [uninstall_mapmapfile] Error 1 (ignored)
rm -f -r /usr/share/applications/mapmap.desktop
rmdir /usr/share/applications/ 
rmdir: failed to remove '/usr/share/applications/': Directory not empty
make: [uninstall_desktopfile] Error 1 (ignored)
rm -f -r /usr/share/icons/hicolor/scalable/apps/mapmap.svg
rmdir /usr/share/icons/hicolor/scalable/apps/ 
rmdir: failed to remove '/usr/share/icons/hicolor/scalable/apps/': Directory not empty
make: [uninstall_iconfile] Error 1 (ignored)
rm -f -r /usr/share/mime/packages/mapmap.xml
rmdir /usr/share/mime/packages/ 
rmdir: failed to remove '/usr/share/mime/packages/': Directory not empty
make: [uninstall_mimetypesfile] Error 1 (ignored)

**Comment by marclava** [comment]
This is the normal behavior of the makefile created using qmake; this is why the error is ignored.
Won't fix.
